#!/usr/bin/env bash
# ============================================================
#  Bake the toolchain environment permanently into ~/.bashrc
#
#  After this, every new shell already has:
#     idf.py / esptool            (ESP-IDF)
#     gradle / adb / sdkmanager   (Android)
#
#  No alias. No "source export.sh". No banner spam.
#
#  v2 fixes:
#    - captures ESP-IDF's PATH in a CLEAN subshell, so the diff is
#      correct even if IDF was already active in your shell
#    - removes duplicate blocks left by setup-android-wsl.sh
#    - JAVA_HOME is resolved once and baked as a literal path, so
#      there is no nested command substitution in .bashrc
#
#  Idempotent: re-run any time (e.g. after upgrading ESP-IDF).
#
#  Usage:  bash setup-shell-env.sh
# ============================================================
set -euo pipefail

BASHRC="$HOME/.bashrc"
START="# carrr-toolchain-env-start"
END="# carrr-toolchain-env-end"
IDF_EXPORT="$HOME/esp/esp-idf/export.sh"
GRADLE_BIN="$HOME/android-tools/gradle-8.7/bin"
CLEAN_PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

touch "$BASHRC"

# ---------------------------------------------------------------
# 1. strip anything we (or the old android script) added before
# ---------------------------------------------------------------
echo "== cleaning previous entries =="
if grep -q "$START" "$BASHRC" 2>/dev/null; then
    sed -i "/$START/,/$END/d" "$BASHRC"
    echo "   removed previous managed block"
fi
sed -i '/# ---- Android build toolchain ----/d' "$BASHRC" 2>/dev/null || true
sed -i '/# ---- ESP-IDF ----/d'                 "$BASHRC" 2>/dev/null || true
sed -i '/^export JAVA_HOME=/d'                  "$BASHRC" 2>/dev/null || true
sed -i '/^export ANDROID_HOME=/d'               "$BASHRC" 2>/dev/null || true
sed -i '/cmdline-tools\/latest\/bin/d'          "$BASHRC" 2>/dev/null || true
sed -i '/alias get_idf=/d'                      "$BASHRC" 2>/dev/null || true

# ---------------------------------------------------------------
# 2. capture the ESP-IDF environment in a PRISTINE subshell
# ---------------------------------------------------------------
IDF_PATH_V=""
IDF_TOOLS_V=""
IDF_PY_V=""
ADDED=""

if [ -f "$IDF_EXPORT" ]; then
    echo "== capturing ESP-IDF environment (clean subshell) =="
    OUT="$(env -i HOME="$HOME" PATH="$CLEAN_PATH" bash -c \
          '. "$HOME/esp/esp-idf/export.sh" >/dev/null 2>&1; \
           printf "%s\n" "$PATH" "$IDF_PATH" "$IDF_TOOLS_PATH" "$IDF_PYTHON_ENV_PATH"' \
          2>/dev/null || true)"

    NEW_PATH="$(printf '%s\n' "$OUT" | sed -n '1p')"
    IDF_PATH_V="$(printf '%s\n' "$OUT" | sed -n '2p')"
    IDF_TOOLS_V="$(printf '%s\n' "$OUT" | sed -n '3p')"
    IDF_PY_V="$(printf '%s\n' "$OUT" | sed -n '4p')"

    # keep only entries the clean PATH did not already have
    IFS=':' read -r -a np <<< "$NEW_PATH"
    IFS=':' read -r -a op <<< "$CLEAN_PATH"
    for p in "${np[@]}"; do
        [ -z "$p" ] && continue
        skip=0
        for q in "${op[@]}"; do
            if [ "$p" = "$q" ]; then skip=1; break; fi
        done
        if [ "$skip" -eq 0 ]; then ADDED="$ADDED:$p"; fi
    done
    ADDED="${ADDED#:}"

    echo "   IDF_PATH            = $IDF_PATH_V"
    echo "   IDF_PYTHON_ENV_PATH = $IDF_PY_V"
    echo "   PATH additions      = $(printf '%s' "$ADDED" | tr ':' '\n' | grep -c . || true) dirs"
else
    echo "!! $IDF_EXPORT not found - skipping ESP-IDF"
fi

# ---------------------------------------------------------------
# 3. resolve JAVA_HOME once, so .bashrc gets a plain literal path
# ---------------------------------------------------------------
JAVA_HOME_V=""
if command -v javac >/dev/null 2>&1; then
    JAVA_HOME_V="$(dirname "$(dirname "$(readlink -f "$(command -v javac)")")")"
    echo "== JAVA_HOME = $JAVA_HOME_V"
else
    echo "!! javac not found - install the JDK first (setup-android-wsl.sh)"
fi

# ---------------------------------------------------------------
# 4. write the block
# ---------------------------------------------------------------
{
    echo ""
    echo "$START"
    echo "# Generated by setup-shell-env.sh - safe to delete this block."
    if [ -n "$IDF_PATH_V" ]; then
        echo ""
        echo "# ---- ESP-IDF ----"
        echo "export IDF_PATH=\"$IDF_PATH_V\""
        [ -n "$IDF_TOOLS_V" ] && echo "export IDF_TOOLS_PATH=\"$IDF_TOOLS_V\""
        [ -n "$IDF_PY_V" ]    && echo "export IDF_PYTHON_ENV_PATH=\"$IDF_PY_V\""
        if [ -n "$ADDED" ]; then
            echo "export PATH=\"$ADDED:\$PATH\""
        else
            echo "# WARNING: could not detect IDF PATH entries; run:"
            echo "#   . \"$IDF_EXPORT\" ; echo \"\$PATH\""
        fi
    fi
    echo ""
    echo "# ---- Android ----"
    [ -n "$JAVA_HOME_V" ] && echo "export JAVA_HOME=\"$JAVA_HOME_V\""
    echo "export ANDROID_HOME=\"\$HOME/Android/Sdk\""
    echo "export PATH=\"\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:$GRADLE_BIN:\$PATH\""
    echo "$END"
} >> "$BASHRC"

echo
echo "=================== DONE ==================="
echo "Block written to $BASHRC"
echo
echo "Open a NEW shell, then:"
echo "  idf.py --version && gradle --version && adb version"
